### ISSUE TITLE
email address for back-end & salting & hashing

### ISSUE THREAD

**Issue by furkee** [yavuzs/arge#1]
Back-end does not require e-mail address and does not use salting & hashing for password storage. These features should be implemented. We should discuss salting & hashing though. We can implement them on front-end as well. That way may be more secure.

**Comment by yavuzs** [comment]
we can implement them on the server side, we will use secure connection in the next version so we won't need hashing on the front side

**Comment by furkee** [comment]
Necessary implementation were pushed to the repo. Validation e-mail system is not there yet. But for now, we are not considering to implement it. So the issue can be closed.
